#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: oran-o2
  labels:
    chart_group: oran-o2
spec:
  releaseName: oran-o2
  chart:
    spec:
      chart: oran-o2
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: oran-o2-static-overrides
      valuesKey: oran-o2-static-overrides.yaml
    - kind: Secret
      name: oran-o2-system-overrides
      valuesKey: oran-o2-system-overrides.yaml
