#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: oran-o2
resources:
  - helmrelease.yaml
secretGenerator:
  - name: oran-o2-static-overrides
    files:
      - oran-o2-static-overrides.yaml
  - name: oran-o2-system-overrides
    files:
      - oran-o2-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
